### PR TITLE
server-audit.sh: add server model info and exclude pg_basebackup from query result.

### PR DESCRIPTION
**Pull request by vitabaks**

### CODE REVIEW

**Comment by lesovsky** [comment]
Hi, 
Could you please explain proposed changes related to `pgReplicaCount` query. It seems, proposed query works as same as old one - shows the same info, but just using another value.

**Comment by vitabaks** [comment]
Hi @lesovsky 
The condition "where application_name ! = 'pg_basebackup'" is necessary to exclude backup jobs (or reinit replicas).

Here are some examples:

result with the condition 'walreceiver':
  Replica count:             **0** -- {**pg_basebackup: {10.129.50.50, 10.129.50.50}**, drm-pgnode02: {10.129.50.34}, drm-pgnode01: {10.129.50.33}}

It should be like this (_where application_name != 'pg_basebackup'_):
 Replica count:             2 -- {drm-pgnode02: {10.129.50.34}, drm-pgnode01: {10.129.50.33}}

**Comment by lesovsky** [comment]
I see, you're talking about `pgReplicaList` query, but I've asked about `pgReplicaCount`. 
Current query also doesn't account pg_basebackup connections, and proposed change looks unnecessary.
But I suppose pgReplicaCount query changed in reason to look "similarly" as pgReplicaList query, isn't?

**Comment by vitabaks** [comment]
`pgReplicaCount`: In the primary_conninfo can be set to а custom of "application_name" value. In this case, application_name will not equal the value of "walreceiver".
And as a result, you get "Replica count: 0" although in fact they are, just for these replicas is set to "application_name".

**Comment by Melkij** [comment]
> primary_conninfo parameter can be set to а custom of "application_name" value
Same thing for pg_basebackup: application_name is not hardcoded. For example, `pg_basebackup --dbname='user=postgres port=5432 application_name=foo' -X stream` is correct and will launch two replication connection with application_name "foo".

**Comment by vitabaks** [comment]
> and will launch two replication connection with application_name "foo"

@Melkij  You're right.

But I think this is a rather rare case of using pg_basebackup in conjunction with the application_name parameter.

**Comment by Melkij** [comment]
Well, maybe it's better to have "replication connections" without a filter?
With `application_name != 'pg_basebackup'` we will also see all logical decoding connections. Usually they are not replicas

**Comment by vyegorov** [comment]
I think we're best off with:
- remove any `where application_name` filters
- rename entry to be `Streaming connections` instead of `Replicas`.

**Comment by lesovsky** [comment]
Have no objections too, thanks!

**Pull request merged**
